import path from "node:path"
import { urlPath } from "../i18n-slug/index.js"

/**
 * _redirects for Cloudflare Pages: one permanent redirect per alias.
 *
 * alias-redirects writes an HTML page at every alias that refreshes to the page
 * and names it as canonical. That keeps working on any host and for the SPA
 * router, but a crawler is first answered 200 and has to read the HTML to learn
 * the page moved. Pages follows a _redirects rule even where an asset exists at
 * the path, so the same aliases answer 301 with the new address instead, and
 * the HTML pages stay as the fallback everywhere else.
 *
 * Sources and destinations are URL paths in the canonical link's form:
 * writing/foo -> /writing/foo, writing/index -> /writing/ (and /writing, so a
 * folder takes one hop either way), essays/index -> /essays/.
 */

// Pages' limit on static rules in one _redirects file.
const STATIC_LIMIT = 2000

const toPath = (slug) => "/" + encodeURI(urlPath(slug))

// An alias is a slug, or a path relative to the page as alias-redirects reads it.
function resolveAlias(slug, alias) {
  if (!/^\.\.?(\/|$)/.test(alias)) return alias
  return path.posix.normalize(path.posix.join(urlPath(slug), "..", alias))
}

/**
 * The redirect rules for these pages, as [source, destination] pairs sorted by
 * source. An alias that is itself a page is skipped: Pages would apply the rule
 * over the page and hide it. The first page to claim an alias keeps it.
 */
export function redirectRules(pages) {
  const live = new Set(pages.map((data) => data.slug))
  const rules = new Map()
  for (const data of pages) {
    const destination = toPath(data.slug)
    for (const alias of data.aliases ?? []) {
      const slug = resolveAlias(data.slug, alias)
      if (live.has(slug)) continue
      const source = toPath(slug)
      const sources =
        source.length > 1 && source.endsWith("/") ? [source, source.slice(0, -1)] : [source]
      for (const from of sources) {
        if (from !== destination && !rules.has(from)) rules.set(from, destination)
      }
    }
  }
  return [...rules].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
}

export function generateRedirects(pages) {
  const rules = redirectRules(pages)
  if (rules.length > STATIC_LIMIT) {
    console.warn(`_redirects: ${rules.length} rules, over Pages' limit of ${STATIC_LIMIT}`)
  }
  const lines = [
    "# Generated by presence-feeds from page aliases. Each old address answers",
    "# 301 with its page; the alias HTML pages remain for other hosts.",
    ...rules.map(([from, to]) => `${from} ${to} 301`),
    "",
  ]
  return lines.join("\n")
}
